included:
  - Sources

disabled_rules:
  - unused_setter_value
  - cyclomatic_complexity
  - identifier_name
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - legacy_hashing
